export const dataTestimonials = [
  {
    id: 1,
    name: "Bartolomiu",
    work: "Fundador - Dev",
    testimonial: "Texto de ejemplo",
    image: "/assets/profile1.png",
  },
  {
    id: 2,
    name: "OfficialCrow",
    work: "Fundador",
    testimonial: "Texto de ejemplo",
    image: "/assets/profile2.png",
  },
  {
    id: 3,
    name: "Lucas Martínez",
    work: "Founder",
    testimonial: "Muy buena landing page SPA sobre como hacer un banco",
    image: "/assets/profile3.png",
  },
  {
    id: 4,
    name: "Vicente Calvo",
    work: "Founder",
    testimonial: "Muy buena landing page SPA sobre como hacer un banco",
    image: "/assets/profile4.png",
  },
  {
    id: 5,
    name: "Patricia García",
    work: "Founder",
    testimonial: "Muy buena landing page SPA sobre como hacer un banco",
    image: "/assets/profile1.png",
  },
  {
    id: 6,
    name: "Raúl Vidal",
    work: "Founder",
    testimonial: "Muy buena landing page SPA sobre como hacer un banco",
    image: "/assets/profile3.png",
  },
  {
    id: 7,
    name: "Raúl Vidal",
    work: "Founder",
    testimonial: "Muy buena landing page SPA sobre como hacer un banco",
    image: "/assets/profile3.png",
  },
  {
    id: 8,
    name: "Raúl Vidal",
    work: "Founder",
    testimonial: "Muy buena landing page SPA sobre como hacer un banco",
    image: "/assets/profile3.png",
  },
  {
    id: 9,
    name: "Raúl Vidal",
    work: "Founder",
    testimonial: "Muy buena landing page SPA sobre como hacer un banco",
    image: "/assets/profile3.png",
  },
  {
    id: 10,
    name: "Raúl Vidal",
    work: "Founder",
    testimonial: "Muy buena landing page SPA sobre como hacer un banco",
    image: "/assets/profile3.png",
  },
];
